from state import State
from langchain_core.messages import (
    SystemMessage,
    HumanMessage,
    ToolMessage,
)
from langchain_mistralai import ChatMistralAI
from config import params
from langchain_core.messages.ai import AIMessage
from components.tools import web_search, scrape_url
from dotenv import load_dotenv
from langgraph.prebuilt import ToolNode
from langgraph.graph import END
from langgraph.types import Send


load_dotenv()

llm = ChatMistralAI(model_name=params["llm_model"], temperature=params["temperature"])
tools = [web_search, scrape_url]

search_llm_with_tools = llm.bind_tools([web_search])
scraper_llm_with_tools = llm.bind_tools([scrape_url])
writer_llm_with_tools = llm.bind_tools([web_search])
critic_llm = llm

# Single tool node, shared by whichever part of the graph needs it
# (used by the Writer <-> Tool loop below)
tool_node = ToolNode(tools)


SEARCH_SYSTEM_PROMPT = (
    "You are the Search Agent in a multi-agent research system. "
    "Your only task is to find relevant URLs using the web_search tool. "
    "For every research request: "
    "- Understand the research topic. "
    "- Generate effective search queries. "
    "- Use the web_search tool to find relevant sources. "
    "- Select the most useful, reliable, and informative URLs. "
    "- Avoid duplicate URLs. "
    "- Prioritize authoritative, recent, and high-quality sources. "
    "Always call the web_search tool - do not answer from memory."
)

SCRAPER_SYSTEM_PROMPT = (
    "You are the Content Extraction Agent in a multi-agent research system. "
    "Your task is to perform deep reading of web pages discovered by the "
    "Search Agent. Use the scrape_url tool to extract page content. "
    "Always call the scrape_url tool with the given URL - do not answer from memory."
)

WRITER_SYSTEM_PROMPT = (
    "You are the Writer Agent in a multi-agent research system. "
    "Your responsibility is to create a comprehensive, well-structured, "
    "and factual research report using the information provided by the "
    "Search Agent and Scraper Agent. "

    "You will receive search results, extracted web content, facts, "
    "statistics, examples, and source URLs gathered during the research process. "
    "Your task is to synthesize this information into a coherent report "
    "that directly answers the research objective. "

    "Your objectives are: "
    "1. Combine information from multiple sources into a unified report. "
    "2. Prioritize factual accuracy and clarity. "
    "3. Remove duplicate or redundant information. "
    "4. Present findings in a logical and professional manner. "
    "5. Preserve important evidence, statistics, and examples. "
    "6. Ensure all major findings are supported by the provided research. "

    "Do not invent facts, statistics, or sources. "
    "Do not introduce information that is not present in the provided research. "
    "If the research contains conflicting information, acknowledge the disagreement "
    "and present both perspectives objectively. "

    "Generate the report using the following structure:\n\n"

    "# Introduction\n"
    "- Briefly explain the topic and its significance.\n\n"

    "# Key Findings\n"
    "- Present the most important insights, facts, statistics, trends, "
    "and evidence gathered during the research.\n"
    "- Organize findings into logical sections when appropriate.\n\n"

    "# Conclusion\n"
    "- Summarize the most important takeaways from the research.\n"
    "- Provide an objective final assessment based on the available evidence.\n\n"

    "# Sources\n"
    "- List every unique source URL used during the research.\n"

    "Your output should contain only the final research report."
)

CRITIC_SYSTEM_PROMPT = (
    "You are the Critic Agent in a multi-agent research system. "
    "Your responsibility is to evaluate the quality, completeness, "
    "accuracy, and structure of a research report generated by the Writer Agent. "

    "You must assess the report according to the following criteria:\n"

    "1. Accuracy (0-25 points)\n"
    "- Are the claims supported by the provided research?\n"
    "- Does the report avoid hallucinations and unsupported statements?\n\n"

    "2. Completeness (0-25 points)\n"
    "- Does the report sufficiently address the research objective?\n"
    "- Are important findings missing?\n\n"

    "3. Clarity and Organization (0-25 points)\n"
    "- Is the report well-structured and easy to understand?\n"
    "- Are Introduction, Key Findings, Conclusion, and Sources present?\n\n"

    "4. Source Usage (0-25 points)\n"
    "- Are findings properly grounded in the gathered research?\n"
    "- Are source URLs included?\n"
    "- Are duplicate or irrelevant sources avoided?\n\n"

    "Scoring:\n"
    "- 90-100: Excellent\n"
    "- 75-89: Good\n"
    "- 60-74: Needs Improvement\n"
    "- Below 60: Poor\n\n"

    "Approval Rules:\n"
    "- APPROVED if score >= 75.\n"
    "- REJECTED if score < 75.\n"

    "When rejecting a report, clearly explain what is missing or incorrect "
    "so the Writer Agent can improve the next version.\n\n"

    "Your response MUST start with exactly one of these two lines "
    "(this is important, it is parsed by code):\n"
    "Status: APPROVED\n"
    "or\n"
    "Status: REJECTED\n\n"

    "Then continue with:\n\n"
    "Score: <0-100>\n\n"
    "Strengths:\n"
    "- ...\n\n"
    "Issues:\n"
    "- ...\n\n"
    "Recommendations:\n"
    "- ...\n"
)


# ---------------------------------------------------------------------------
# SEARCH NODE
# ---------------------------------------------------------------------------
def search_node(state: State) -> dict:
    """
    Asks the Search Agent (LLM) to decide on a good search query and request
    the web_search tool. We then actually RUN that tool ourselves and store
    the real list of URLs in state - binding a tool only makes the LLM ask
    to use it, it does not run it for you.
    """
    topic = state["topic"]

    user_prompt = f"Find recent, reliable and appropriate website URLs about the topic: {topic}"

    ai_message = search_llm_with_tools.invoke(
        [
            SystemMessage(content=SEARCH_SYSTEM_PROMPT),
            HumanMessage(content=user_prompt),
        ]
    )

    urls: list[str] = []

    for call in ai_message.tool_calls or []:
        if call["name"] == "web_search":
            result = web_search.invoke(call["args"])
            urls.extend(result)

    # remove duplicates while keeping the original order
    urls = list(dict.fromkeys(urls))

    return {"urls": urls}


# ---------------------------------------------------------------------------
# SCRAPING NODES
# ---------------------------------------------------------------------------
def route_scraping(state: State) -> list:
    """Creates one parallel branch per URL, each branch gets its own {"url": ...} state."""
    return [Send("single_scraper", {"url": url}) for url in state["urls"]]


def single_scraper(state: dict) -> dict:
    """
    Runs inside one Send() branch, so state only has the single key "url"
    (NOT the full graph State, and NOT "urls").
    """
    url = state["url"]

    user_prompt = f"Scrape the URL: {url}"

    ai_message = scraper_llm_with_tools.invoke(
        [
            SystemMessage(content=SCRAPER_SYSTEM_PROMPT),
            HumanMessage(content=user_prompt),
        ]
    )

    scraped_text = ""
    for call in ai_message.tool_calls or []:
        if call["name"] == "scrape_url":
            scraped_text = scrape_url.invoke(call["args"])

    if not scraped_text:
        scraped_text = f"No content could be scraped from {url}"

    return {"scraped_content": [scraped_text]}


# ---------------------------------------------------------------------------
# WRITER NODE
# ---------------------------------------------------------------------------
def writer_node(state: State) -> dict:
    """
    Writer node.

    Case 1:
        Called after ToolNode. Continues the existing conversation so the
        model can read the tool output and produce the final draft.

    Case 2:
        Called after START or after critic rejection. Creates a new prompt.
    """

    messages = state.get("messages", [])

    # -------------------------------------------------------
    # CASE 1: Returning from ToolNode
    # -------------------------------------------------------
    if messages and isinstance(messages[-1], ToolMessage):
        response = writer_llm_with_tools.invoke(
            [
                SystemMessage(content=WRITER_SYSTEM_PROMPT),
                *messages,
            ]
        )

        return {"messages": [response]}

    # -------------------------------------------------------
    # CASE 2: Starting a fresh draft / rewrite
    # -------------------------------------------------------
    attempt = state.get("attempt", 0) + 1

    topic = state["topic"]
    feedback = state.get("feedback", "")

    if attempt == 1:
        user_prompt = f"""
Write a detailed report about:

Topic:
{topic}

If current statistics, trends, or news are needed,
use the web search tool before writing.
"""
    else:
        user_prompt = f"""
Your previous report was rejected.

Topic:
{topic}

Reviewer Feedback:
{feedback}

Rewrite the report.

Fix every issue mentioned.

If current information is needed,
use the web search tool.
"""

    response = writer_llm_with_tools.invoke(
        [
            SystemMessage(content=WRITER_SYSTEM_PROMPT),
            *messages,
            HumanMessage(content=user_prompt),
        ]
    )

    return {
        "messages": [
            HumanMessage(content=user_prompt),
            response,
        ],
        "attempt": attempt,
    }


# ---------------------------------------------------------------------------
# EXTRACT DRAFT NODE
# ---------------------------------------------------------------------------
def extract_draft_node(state: State):
    draft = ""
    for msg in reversed(state["messages"]):
        if isinstance(msg, AIMessage):
            if isinstance(msg.content, str) and msg.content.strip():
                draft = msg.content.strip()
                break

    print("\nGenerated Draft:\n")
    print(draft)

    return {"report": draft}


# ---------------------------------------------------------------------------
# CRITIC NODE
# ---------------------------------------------------------------------------
def critic_node(state: State) -> dict:
    draft = state["report"]

    prompt = f"Review this report draft:\n{draft}\n\nGive your review or feedback."

    response = critic_llm.invoke([("system", CRITIC_SYSTEM_PROMPT), ("human", prompt)])

    review = response.content.strip()

    # The prompt forces the model to start with a "Status: APPROVED/REJECTED"
    # line, so we look at that specific line rather than scanning the whole
    # text (scanning the whole text is unreliable - the word "APPROVED" or
    # "REJECTED" can show up again later inside the Issues/Recommendations).
    status_line = review.splitlines()[0].upper() if review else ""
    is_approved = "APPROVED" in status_line and "REJECTED" not in status_line

    feedback = review  # Issues + Recommendations are useful context for a rewrite, so we keep it all

    verdict = "APPROVED" if is_approved else "REJECTED"
    print(f"[Verdict: {verdict}]")
    print(f"[Feedback]:\n{feedback}")

    return {"feedback": feedback, "is_approved": is_approved}


# ---------------------------------------------------------------------------
# ROUTERS
# ---------------------------------------------------------------------------
def should_use_tool(state: State):
    last_message = state["messages"][-1]

    if isinstance(last_message, AIMessage) and last_message.tool_calls:
        return "tools"
    return "extract_draft"


def should_stop_looping(state: State):
    if state["is_approved"]:
        print("Report has been approved\n")
        return END
    if state["attempt"] >= 3:
        print("Reached max attempts")
        return END
    return "writer"